apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: rabbit
spec:
  selector:
    app: rabbit
  ports:
    - name: default
      protocol: TCP
      port: 5672
      targetPort: 5672
  type: ClusterIP